### ISSUE TITLE
components.pomodoro_components.py Profile class issue + collateral

### ISSUE THREAD

**Issue by ddaarrrryyll** [vichannnnn/Pomodoro-chan#10]
Reported: /roominfo changes room owner's name to the name of user who interacted with button

Expected: only invoker of command can interact with button, will solve issue

Potential issue:
`return ctx.interaction.user == ctx.user` always true

**Comment by ddaarrrryyll** [comment]
skull traced wrong, issue shld be under `display_handler.py`
 `embed = hikari.Embed(title=f"{ctx.interaction.user}'s Study Room", description=description)`

**Comment by vichannnnn** [comment]
LGTM
